# Use a base image
FROM node:10

# Create a workdir
RUN mkdir -p /app
WORKDIR /app

# Install sqlite3
RUN apt-get update
RUN apt-get --yes install sqlite3

# Install npm packages
COPY package.json /app
RUN npm install
